
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowRMM`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2025, 
        `title`="snowRMM: Rasch Mixture, LCA, and Test Equating Analysis", 
        `publisher`="(Version 5.8.7) [jamovi module]. URL https://github.com/hyunsooseol/snowRMM", 
        `url`="https://github.com/hyunsooseol/snowRMM"), 
    `mixRasch`=list(
        `type`="software", 
        `author`="Willse, J.", 
        `year`=2014, 
        `title`="mixRasch: Mixture Rasch Models with JMLE", 
        `publisher`="[R package]. URL https://github.com/cran/mixRasch.git"), 
    `mixRaschTools`=list(
        `type`="software", 
        `author`="Trantham, P.", 
        `year`=2019, 
        `title`="mixRaschTools: Plotting and Average Theta Functions for Multiple Class Mixed Rasch Models", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=mixRaschTools"), 
    `boot`=list(
        `type`="software", 
        `author`="Canty, A., & Ripley, B.", 
        `year`=2020, 
        `title`="boot: Bootstrap R (S-Plus) Functions", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=boot"), 
    `WrightMap`=list(
        `type`="software", 
        `author`="Irribarra, T., & Freund, R.", 
        `year`=2020, 
        `title`="WrightMap: IRT item-person map with ConQuest integration", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=WrightMap"), 
    `ShinyItemAnalysis`=list(
        `type`="software", 
        `author`="Martinkova, P., & Drabinova, A.", 
        `year`=2018, 
        `title`="ShinyItemAnalysis: for teaching psychometrics and to enforce routine analysis of educational tests", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=ShinyItemAnalysis"), 
    `poLCA`=list(
        `type`="software", 
        `author`="Linzer, D., & Lewis, J.", 
        `year`=2022, 
        `title`="poLCA: An R Package for Polytomous Variable Latent Class Analysis", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=poLCA"), 
    `equi`=list(
        `type`="software", 
        `author`="Wolodzko, T.", 
        `year`=2020, 
        `title`="equi: Equipercentile Equating", 
        `publisher`="[R package]. URL https://github.com/twolodzko/equi/"), 
    `equate`=list(
        `type`="software", 
        `author`="Albano, A.", 
        `year`=2018, 
        `title`="equate: Observed-Score Linking and Equating", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=equate"), 
    `tidyLPA`=list(
        `type`="software", 
        `author`="Rosenberg, J., Beymer, P., Anderson, D., Van Lissa, C., & Schmidt, J.", 
        `year`=2021, 
        `title`="tidyLPA: Easily Carry Out Latent Profile Analysis (LPA) Using Open-Source or Commercial Software", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=tidyLPA"), 
    `iarm`=list(
        `type`="software", 
        `author`="Mueller, M., & Santiago, P.", 
        `year`=2020, 
        `title`="iarm: Item Analysis in Rasch Models", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=iarm"), 
    `eRm`=list(
        `type`="software", 
        `author`="Mair, P., Hatzinger, R., Maier, M., Rusch, T., & Debelak R.", 
        `year`=2021, 
        `title`="eRm: Extended Rasch Modeling", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=eRm"), 
    `pairwise`=list(
        `type`="software", 
        `author`="Heine,J-H.", 
        `year`=2023, 
        `title`="pairwise: Rasch Model Parameters by Pairwise Algorithm", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=pairwise"), 
    `tidySEM`=list(
        `type`="software", 
        `author`="van Lissa, C., Garnier-Villarreal, M., Gootjes, F.", 
        `year`=2024, 
        `title`="tidySEM: Tidy Structural Equation Modeling", 
        `publisher`="[R package]. URL https://CRAN.R-project.org/package=tidySEM"))
