
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowRMM`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2022, 
        `title`="snowRMM: Rasch Mixture Model for jamovi", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/snowRMM"), 
    `mixRasch`=list(
        `type`="software", 
        `author`="Willse, J.", 
        `year`=2014, 
        `title`="mixRasch: Mixture Rasch Models with JMLE", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=mixRasch"), 
    `mixRaschTools`=list(
        `type`="software", 
        `author`="Trantham, P.", 
        `year`=2019, 
        `title`="mixRaschTools: Plotting and Average Theta Functions for Multiple Class Mixed Rasch Models", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=mixRaschTools"), 
    `boot`=list(
        `type`="software", 
        `author`="Canty, A., & Ripley, B.", 
        `year`=2020, 
        `title`="boot: Bootstrap R (S-Plus) Functions", 
        `publisher`="[R package]. Retrieved from  https://CRAN.R-project.org/package=boot"), 
    `WrightMap`=list(
        `type`="software", 
        `author`="Irribarra,T., & Freund, R.", 
        `year`=2020, 
        `title`="Wright Map: IRT item-person map with ConQuest integration", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=WrightMap"), 
    `ShinyItemAnalysis`=list(
        `type`="software", 
        `author`="Martinkova, P., & Drabinova, A.", 
        `year`=2018, 
        `title`="ShinyItemAnalysis: for teaching psychometrics and to enforce routine analysis of educational tests", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=ShinyItemAnalysis"), 
    `poLCA`=list(
        `type`="software", 
        `author`="Linzer,D., & Lewis, J.", 
        `year`=2021, 
        `title`="poLCA: An R Package for Polytomous Variable Latent Class Analysis", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=poLCA"))
