
# This file is automatically generated, you probably don't want to edit this

bfitOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            step = 1,
            type = "RSM",
            bn = 1000,
            bfit = TRUE,
            inplot = FALSE,
            outplot = FALSE, ...) {

            super$initialize(
                package='snowRMM',
                name='bfit',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..step <- jmvcore::OptionInteger$new(
                "step",
                step,
                min=1,
                default=1)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "RSM",
                    "PCM"),
                default="RSM")
            private$..bn <- jmvcore::OptionInteger$new(
                "bn",
                bn,
                min=2,
                default=1000)
            private$..bfit <- jmvcore::OptionBool$new(
                "bfit",
                bfit,
                default=TRUE)
            private$..inplot <- jmvcore::OptionBool$new(
                "inplot",
                inplot,
                default=FALSE)
            private$..outplot <- jmvcore::OptionBool$new(
                "outplot",
                outplot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..step)
            self$.addOption(private$..type)
            self$.addOption(private$..bn)
            self$.addOption(private$..bfit)
            self$.addOption(private$..inplot)
            self$.addOption(private$..outplot)
        }),
    active = list(
        vars = function() private$..vars$value,
        step = function() private$..step$value,
        type = function() private$..type$value,
        bn = function() private$..bn$value,
        bfit = function() private$..bfit$value,
        inplot = function() private$..inplot$value,
        outplot = function() private$..outplot$value),
    private = list(
        ..vars = NA,
        ..step = NA,
        ..type = NA,
        ..bn = NA,
        ..bfit = NA,
        ..inplot = NA,
        ..outplot = NA)
)

bfitResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        bfit = function() private$.items[["bfit"]],
        inplot = function() private$.items[["inplot"]],
        outplot = function() private$.items[["outplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrap Item Fit")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="snowRMM"))
            self$add(jmvcore::Table$new(
                options=options,
                name="bfit",
                title="Bootstrap item fit",
                visible="(bfit)",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="snowRMM",
                columns=list(
                    list(
                        `name`="binfit[in]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Infit"),
                    list(
                        `name`="binfit[out]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Outfit"),
                    list(
                        `name`="l[infit]", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="u[infit]", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="l[outfit]", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="u[outfit]", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="inplot",
                title="Infit distribution",
                width=600,
                height=450,
                visible="(inplot)",
                renderFun=".inplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="outplot",
                title="Outfit distribution",
                width=600,
                height=450,
                visible="(outplot)",
                renderFun=".outplot"))}))

bfitBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowRMM',
                name = 'bfit',
                version = c(1,0,0),
                options = options,
                results = bfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bootstrap Item Fit
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param step .
#' @param type .
#' @param bn .
#' @param bfit .
#' @param inplot .
#' @param outplot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$bfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$inplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$outplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$bfit$asDF}
#'
#' \code{as.data.frame(results$bfit)}
#'
#' @export
bfit <- function(
    data,
    vars,
    step = 1,
    type = "RSM",
    bn = 1000,
    bfit = TRUE,
    inplot = FALSE,
    outplot = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('bfit requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- bfitOptions$new(
        vars = vars,
        step = step,
        type = type,
        bn = bn,
        bfit = bfit,
        inplot = inplot,
        outplot = outplot)

    analysis <- bfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
