
# This file is automatically generated, you probably don't want to edit this

bfitOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            step = 1,
            bn = 100,
            binfit = TRUE,
            boutfit = TRUE, ...) {

            super$initialize(
                package='snowRMM',
                name='bfit',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..step <- jmvcore::OptionInteger$new(
                "step",
                step,
                min=1,
                default=1)
            private$..bn <- jmvcore::OptionInteger$new(
                "bn",
                bn,
                min=2,
                default=100)
            private$..binfit <- jmvcore::OptionBool$new(
                "binfit",
                binfit,
                default=TRUE)
            private$..boutfit <- jmvcore::OptionBool$new(
                "boutfit",
                boutfit,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..step)
            self$.addOption(private$..bn)
            self$.addOption(private$..binfit)
            self$.addOption(private$..boutfit)
        }),
    active = list(
        vars = function() private$..vars$value,
        step = function() private$..step$value,
        bn = function() private$..bn$value,
        binfit = function() private$..binfit$value,
        boutfit = function() private$..boutfit$value),
    private = list(
        ..vars = NA,
        ..step = NA,
        ..bn = NA,
        ..binfit = NA,
        ..boutfit = NA)
)

bfitResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        item = function() private$.items[["item"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrap Item Fit",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    binfit = function() private$.items[["binfit"]],
                    boutfit = function() private$.items[["boutfit"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="item",
                            title="Bootstrap Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="binfit",
                            title="Bootstraped item infit",
                            visible="(binfit)",
                            rows="(vars)",
                            clearWith=list(
                                "vars"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="infitlow", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="infithigh", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="boutfit",
                            title="Bootstraped item outfit",
                            visible="(boutfit)",
                            rows="(vars)",
                            clearWith=list(
                                "vars"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="outfitlow", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="outfithigh", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))}))$new(options=options))}))

bfitBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowRMM',
                name = 'bfit',
                version = c(1,0,0),
                options = options,
                results = bfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bootstrap Item Fit
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param step .
#' @param bn .
#' @param binfit .
#' @param boutfit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$item$binfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item$boutfit} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
bfit <- function(
    data,
    vars,
    step = 1,
    bn = 100,
    binfit = TRUE,
    boutfit = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('bfit requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- bfitOptions$new(
        vars = vars,
        step = step,
        bn = bn,
        binfit = binfit,
        boutfit = boutfit)

    analysis <- bfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
