
# This file is automatically generated, you probably don't want to edit this

difOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            facs = NULL,
            z = TRUE,
            plot1 = FALSE,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowRMM",
                name="dif",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..z <- jmvcore::OptionBool$new(
                "z",
                z,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..facs)
            self$.addOption(private$..z)
            self$.addOption(private$..plot1)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        facs = function() private$..facs$value,
        z = function() private$..z$value,
        plot1 = function() private$..plot1$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..facs = NA,
        ..z = NA,
        ..plot1 = NA,
        ..width1 = NA,
        ..height1 = NA)
)

difResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        z = function() private$.items[["z"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Differential Item Functioning")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="z",
                title="Z statistics",
                visible="(z)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "group"),
                refs="eRm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="zstat", 
                        `title`="Statistic"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Item comparisons",
                visible="(plot1)",
                renderFun=".plot1",
                refs="iarm",
                clearWith=list(
                    "vars",
                    "group",
                    "width1",
                    "height1")))}))

difBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "dif",
                version = c(1,0,0),
                options = options,
                results = difResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Differential Item Functioning
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param facs .
#' @param z .
#' @param plot1 .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$z} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$z$asDF}
#'
#' \code{as.data.frame(results$z)}
#'
#' @export
dif <- function(
    data,
    vars,
    facs,
    z = TRUE,
    plot1 = FALSE,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dif requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(facs), facs, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- difOptions$new(
        vars = vars,
        facs = facs,
        z = z,
        plot1 = plot1,
        width1 = width1,
        height1 = height1)

    analysis <- difClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

