
# This file is automatically generated, you probably don't want to edit this

difOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            facs = NULL,
            model = "dicho",
            z = FALSE,
            plot1 = FALSE,
            width1 = 500,
            height1 = 500,
            comp = FALSE,
            plot2 = FALSE,
            angle = 0,
            width2 = 500,
            height2 = 500,
            plot3 = FALSE,
            width3 = 500,
            height3 = 500,
            plot4 = FALSE,
            width4 = 500,
            height4 = 500,
            plot5 = FALSE,
            width5 = 500,
            height5 = 500,
            comp1 = FALSE,
            plot6 = FALSE,
            angle1 = 0,
            width6 = 500,
            height6 = 500,
            plot7 = FALSE,
            width7 = 500,
            height7 = 500,
            plot8 = FALSE,
            width8 = 500,
            height8 = 500, ...) {

            super$initialize(
                package="snowRMM",
                name="dif",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "dicho",
                    "partial"),
                default="dicho")
            private$..z <- jmvcore::OptionBool$new(
                "z",
                z,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..width4 <- jmvcore::OptionInteger$new(
                "width4",
                width4,
                default=500)
            private$..height4 <- jmvcore::OptionInteger$new(
                "height4",
                height4,
                default=500)
            private$..plot5 <- jmvcore::OptionBool$new(
                "plot5",
                plot5,
                default=FALSE)
            private$..width5 <- jmvcore::OptionInteger$new(
                "width5",
                width5,
                default=500)
            private$..height5 <- jmvcore::OptionInteger$new(
                "height5",
                height5,
                default=500)
            private$..comp1 <- jmvcore::OptionBool$new(
                "comp1",
                comp1,
                default=FALSE)
            private$..plot6 <- jmvcore::OptionBool$new(
                "plot6",
                plot6,
                default=FALSE)
            private$..angle1 <- jmvcore::OptionNumber$new(
                "angle1",
                angle1,
                min=0,
                max=90,
                default=0)
            private$..width6 <- jmvcore::OptionInteger$new(
                "width6",
                width6,
                default=500)
            private$..height6 <- jmvcore::OptionInteger$new(
                "height6",
                height6,
                default=500)
            private$..plot7 <- jmvcore::OptionBool$new(
                "plot7",
                plot7,
                default=FALSE)
            private$..width7 <- jmvcore::OptionInteger$new(
                "width7",
                width7,
                default=500)
            private$..height7 <- jmvcore::OptionInteger$new(
                "height7",
                height7,
                default=500)
            private$..plot8 <- jmvcore::OptionBool$new(
                "plot8",
                plot8,
                default=FALSE)
            private$..width8 <- jmvcore::OptionInteger$new(
                "width8",
                width8,
                default=500)
            private$..height8 <- jmvcore::OptionInteger$new(
                "height8",
                height8,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..facs)
            self$.addOption(private$..model)
            self$.addOption(private$..z)
            self$.addOption(private$..plot1)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..comp)
            self$.addOption(private$..plot2)
            self$.addOption(private$..angle)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..width4)
            self$.addOption(private$..height4)
            self$.addOption(private$..plot5)
            self$.addOption(private$..width5)
            self$.addOption(private$..height5)
            self$.addOption(private$..comp1)
            self$.addOption(private$..plot6)
            self$.addOption(private$..angle1)
            self$.addOption(private$..width6)
            self$.addOption(private$..height6)
            self$.addOption(private$..plot7)
            self$.addOption(private$..width7)
            self$.addOption(private$..height7)
            self$.addOption(private$..plot8)
            self$.addOption(private$..width8)
            self$.addOption(private$..height8)
        }),
    active = list(
        vars = function() private$..vars$value,
        facs = function() private$..facs$value,
        model = function() private$..model$value,
        z = function() private$..z$value,
        plot1 = function() private$..plot1$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        comp = function() private$..comp$value,
        plot2 = function() private$..plot2$value,
        angle = function() private$..angle$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        plot3 = function() private$..plot3$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value,
        plot4 = function() private$..plot4$value,
        width4 = function() private$..width4$value,
        height4 = function() private$..height4$value,
        plot5 = function() private$..plot5$value,
        width5 = function() private$..width5$value,
        height5 = function() private$..height5$value,
        comp1 = function() private$..comp1$value,
        plot6 = function() private$..plot6$value,
        angle1 = function() private$..angle1$value,
        width6 = function() private$..width6$value,
        height6 = function() private$..height6$value,
        plot7 = function() private$..plot7$value,
        width7 = function() private$..width7$value,
        height7 = function() private$..height7$value,
        plot8 = function() private$..plot8$value,
        width8 = function() private$..width8$value,
        height8 = function() private$..height8$value),
    private = list(
        ..vars = NA,
        ..facs = NA,
        ..model = NA,
        ..z = NA,
        ..plot1 = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..comp = NA,
        ..plot2 = NA,
        ..angle = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..plot3 = NA,
        ..width3 = NA,
        ..height3 = NA,
        ..plot4 = NA,
        ..width4 = NA,
        ..height4 = NA,
        ..plot5 = NA,
        ..width5 = NA,
        ..height5 = NA,
        ..comp1 = NA,
        ..plot6 = NA,
        ..angle1 = NA,
        ..width6 = NA,
        ..height6 = NA,
        ..plot7 = NA,
        ..width7 = NA,
        ..height7 = NA,
        ..plot8 = NA,
        ..width8 = NA,
        ..height8 = NA)
)

difResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        comp = function() private$.items[["comp"]],
        z = function() private$.items[["z"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]],
        plot5 = function() private$.items[["plot5"]],
        comp1 = function() private$.items[["comp1"]],
        plot6 = function() private$.items[["plot6"]],
        plot7 = function() private$.items[["plot7"]],
        plot8 = function() private$.items[["plot8"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Differential Item Functioning")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Item measure for grouping variable",
                visible="(comp)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "facs",
                    "model"),
                refs="eRm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="g1", 
                        `title`="Group1", 
                        `type`="number"),
                    list(
                        `name`="se1", 
                        `title`="SE1", 
                        `type`="number"),
                    list(
                        `name`="g2", 
                        `title`="Group2", 
                        `type`="number"),
                    list(
                        `name`="se2", 
                        `title`="SE2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="z",
                title="Z statistics",
                visible="(z)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "facs",
                    "model"),
                refs="eRm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="zstat", 
                        `title`="Statistic"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Z plot",
                visible="(plot1)",
                renderFun=".plot1",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "facs",
                    "width1",
                    "height1",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Item Comparison",
                visible="(plot2)",
                renderFun=".plot2",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width2",
                    "height2",
                    "angle",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Scatterplot of item difference",
                visible="(plot3)",
                renderFun=".plot3",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width3",
                    "height3",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Bar plot of item difference",
                visible="(plot4)",
                renderFun=".plot4",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width4",
                    "height4",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot5",
                title="Z plot",
                visible="(plot5)",
                renderFun=".plot5",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "facs",
                    "width5",
                    "height5",
                    "model")))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp1",
                title="Comparison of item difficulties",
                visible="(comp1)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "facs",
                    "model"),
                refs="eRm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="g1", 
                        `title`="Group1", 
                        `type`="number"),
                    list(
                        `name`="g2", 
                        `title`="Group2", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot6",
                title="Comparison plot",
                visible="(plot6)",
                renderFun=".plot6",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width6",
                    "height6",
                    "angle1",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot7",
                title="Scatterplot of item difference",
                visible="(plot7)",
                renderFun=".plot7",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width7",
                    "height7",
                    "model")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot8",
                title="Bar plot of item difference",
                visible="(plot8)",
                renderFun=".plot8",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "facs",
                    "width8",
                    "height8",
                    "model")))}))

difBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "dif",
                version = c(1,0,0),
                options = options,
                results = difResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Differential Item Functioning
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param facs .
#' @param model .
#' @param z .
#' @param plot1 .
#' @param width1 .
#' @param height1 .
#' @param comp .
#' @param plot2 .
#' @param angle .
#' @param width2 .
#' @param height2 .
#' @param plot3 .
#' @param width3 .
#' @param height3 .
#' @param plot4 .
#' @param width4 .
#' @param height4 .
#' @param plot5 .
#' @param width5 .
#' @param height5 .
#' @param comp1 .
#' @param plot6 .
#' @param angle1 .
#' @param width6 .
#' @param height6 .
#' @param plot7 .
#' @param width7 .
#' @param height7 .
#' @param plot8 .
#' @param width8 .
#' @param height8 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$z} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$comp1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot7} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot8} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$comp$asDF}
#'
#' \code{as.data.frame(results$comp)}
#'
#' @export
dif <- function(
    data,
    vars,
    facs,
    model = "dicho",
    z = FALSE,
    plot1 = FALSE,
    width1 = 500,
    height1 = 500,
    comp = FALSE,
    plot2 = FALSE,
    angle = 0,
    width2 = 500,
    height2 = 500,
    plot3 = FALSE,
    width3 = 500,
    height3 = 500,
    plot4 = FALSE,
    width4 = 500,
    height4 = 500,
    plot5 = FALSE,
    width5 = 500,
    height5 = 500,
    comp1 = FALSE,
    plot6 = FALSE,
    angle1 = 0,
    width6 = 500,
    height6 = 500,
    plot7 = FALSE,
    width7 = 500,
    height7 = 500,
    plot8 = FALSE,
    width8 = 500,
    height8 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dif requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(facs), facs, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- difOptions$new(
        vars = vars,
        facs = facs,
        model = model,
        z = z,
        plot1 = plot1,
        width1 = width1,
        height1 = height1,
        comp = comp,
        plot2 = plot2,
        angle = angle,
        width2 = width2,
        height2 = height2,
        plot3 = plot3,
        width3 = width3,
        height3 = height3,
        plot4 = plot4,
        width4 = width4,
        height4 = height4,
        plot5 = plot5,
        width5 = width5,
        height5 = height5,
        comp1 = comp1,
        plot6 = plot6,
        angle1 = angle1,
        width6 = width6,
        height6 = height6,
        plot7 = plot7,
        width7 = width7,
        height7 = height7,
        plot8 = plot8,
        width8 = width8,
        height8 = height8)

    analysis <- difClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

