
# This file is automatically generated, you probably don't want to edit this

equatingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ind = NULL,
            dep = NULL,
            lineq = TRUE,
            contabx = FALSE,
            contaby = FALSE,
            contabxy = FALSE,
            plot = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="equating",
                requiresData=TRUE,
                ...)

            private$..ind <- jmvcore::OptionVariable$new(
                "ind",
                ind,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..lineq <- jmvcore::OptionBool$new(
                "lineq",
                lineq,
                default=TRUE)
            private$..contabx <- jmvcore::OptionBool$new(
                "contabx",
                contabx,
                default=FALSE)
            private$..contaby <- jmvcore::OptionBool$new(
                "contaby",
                contaby,
                default=FALSE)
            private$..contabxy <- jmvcore::OptionBool$new(
                "contabxy",
                contabxy,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..escore <- jmvcore::OptionOutput$new(
                "escore")

            self$.addOption(private$..ind)
            self$.addOption(private$..dep)
            self$.addOption(private$..lineq)
            self$.addOption(private$..contabx)
            self$.addOption(private$..contaby)
            self$.addOption(private$..contabxy)
            self$.addOption(private$..plot)
            self$.addOption(private$..escore)
        }),
    active = list(
        ind = function() private$..ind$value,
        dep = function() private$..dep$value,
        lineq = function() private$..lineq$value,
        contabx = function() private$..contabx$value,
        contaby = function() private$..contaby$value,
        contabxy = function() private$..contabxy$value,
        plot = function() private$..plot$value,
        escore = function() private$..escore$value),
    private = list(
        ..ind = NA,
        ..dep = NA,
        ..lineq = NA,
        ..contabx = NA,
        ..contaby = NA,
        ..contabxy = NA,
        ..plot = NA,
        ..escore = NA)
)

equatingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        lineq = function() private$.items[["lineq"]],
        contabx = function() private$.items[["contabx"]],
        contaby = function() private$.items[["contaby"]],
        contabxy = function() private$.items[["contabxy"]],
        plot = function() private$.items[["plot"]],
        escore = function() private$.items[["escore"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Equating",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="lineq",
                title="Linear equation",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="equi",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`=""),
                    list(
                        `name`="intercept", 
                        `type`="number"),
                    list(
                        `name`="slope", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="contabx",
                title="Contingency table of form x",
                visible="(contabx)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="score", 
                        `type`="integer"),
                    list(
                        `name`="frequency", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="contaby",
                title="Contingency table of form y",
                visible="(contaby)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="score", 
                        `type`="integer"),
                    list(
                        `name`="frequency", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="contabxy",
                title="Contingency table of form x and y",
                visible="(contabxy)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="score_x", 
                        `type`="integer"),
                    list(
                        `name`="score_y", 
                        `type`="integer"),
                    list(
                        `name`="frequency", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Cumulative distribution plot",
                requiresData=TRUE,
                refs="snowRMM",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars")))
            self$add(jmvcore::Output$new(
                options=options,
                name="escore",
                title="Equating score",
                varTitle="xz",
                measureType="nominal",
                clearWith=list(
                    "vars")))}))

equatingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "equating",
                version = c(1,0,0),
                options = options,
                results = equatingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Equating
#'
#' 
#' @param data .
#' @param ind .
#' @param dep .
#' @param lineq .
#' @param contabx .
#' @param contaby .
#' @param contabxy .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$lineq} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contabx} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contaby} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contabxy} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$escore} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lineq$asDF}
#'
#' \code{as.data.frame(results$lineq)}
#'
#' @export
equating <- function(
    data,
    ind,
    dep,
    lineq = TRUE,
    contabx = FALSE,
    contaby = FALSE,
    contabxy = FALSE,
    plot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("equating requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ind)) ind <- jmvcore::resolveQuo(jmvcore::enquo(ind))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ind), ind, NULL),
            `if`( ! missing(dep), dep, NULL))


    options <- equatingOptions$new(
        ind = ind,
        dep = dep,
        lineq = lineq,
        contabx = contabx,
        contaby = contaby,
        contabxy = contabxy,
        plot = plot)

    analysis <- equatingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

