
# This file is automatically generated, you probably don't want to edit this

equatingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ind = NULL,
            dep = NULL,
            contabx = FALSE,
            contabxy = FALSE,
            lineq = TRUE,
            cdfplot = FALSE,
            escore = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="equating",
                requiresData=TRUE,
                ...)

            private$..ind <- jmvcore::OptionVariable$new(
                "ind",
                ind,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..contabx <- jmvcore::OptionBool$new(
                "contabx",
                contabx,
                default=FALSE)
            private$..contabxy <- jmvcore::OptionBool$new(
                "contabxy",
                contabxy,
                default=FALSE)
            private$..lineq <- jmvcore::OptionBool$new(
                "lineq",
                lineq,
                default=TRUE)
            private$..cdfplot <- jmvcore::OptionBool$new(
                "cdfplot",
                cdfplot,
                default=FALSE)
            private$..escore <- jmvcore::OptionBool$new(
                "escore",
                escore,
                default=FALSE)

            self$.addOption(private$..ind)
            self$.addOption(private$..dep)
            self$.addOption(private$..contabx)
            self$.addOption(private$..contabxy)
            self$.addOption(private$..lineq)
            self$.addOption(private$..cdfplot)
            self$.addOption(private$..escore)
        }),
    active = list(
        ind = function() private$..ind$value,
        dep = function() private$..dep$value,
        contabx = function() private$..contabx$value,
        contabxy = function() private$..contabxy$value,
        lineq = function() private$..lineq$value,
        cdfplot = function() private$..cdfplot$value,
        escore = function() private$..escore$value),
    private = list(
        ..ind = NA,
        ..dep = NA,
        ..contabx = NA,
        ..contabxy = NA,
        ..lineq = NA,
        ..cdfplot = NA,
        ..escore = NA)
)

equatingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Equating",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))}))

equatingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equatingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "equating",
                version = c(1,0,0),
                options = options,
                results = equatingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Equating
#'
#' 
#' @param data .
#' @param ind .
#' @param dep .
#' @param contabx .
#' @param contabxy .
#' @param lineq .
#' @param cdfplot .
#' @param escore .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
equating <- function(
    data,
    ind,
    dep,
    contabx = FALSE,
    contabxy = FALSE,
    lineq = TRUE,
    cdfplot = FALSE,
    escore = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("equating requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ind)) ind <- jmvcore::resolveQuo(jmvcore::enquo(ind))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ind), ind, NULL),
            `if`( ! missing(dep), dep, NULL))


    options <- equatingOptions$new(
        ind = ind,
        dep = dep,
        contabx = contabx,
        contabxy = contabxy,
        lineq = lineq,
        cdfplot = cdfplot,
        escore = escore)

    analysis <- equatingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

