
# This file is automatically generated, you probably don't want to edit this

equiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ind = NULL,
            dep = NULL,
            group = NULL,
            design = NULL,
            con = TRUE, ...) {

            super$initialize(
                package="snowRMM",
                name="equi",
                requiresData=TRUE,
                ...)

            private$..ind <- jmvcore::OptionVariable$new(
                "ind",
                ind,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..design <- jmvcore::OptionList$new(
                "design",
                design,
                options=list(
                    "single",
                    "equivalent"))
            private$..con <- jmvcore::OptionBool$new(
                "con",
                con,
                default=TRUE)
            private$..escore <- jmvcore::OptionOutput$new(
                "escore")

            self$.addOption(private$..ind)
            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..design)
            self$.addOption(private$..con)
            self$.addOption(private$..escore)
        }),
    active = list(
        ind = function() private$..ind$value,
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        design = function() private$..design$value,
        con = function() private$..con$value,
        escore = function() private$..escore$value),
    private = list(
        ..ind = NA,
        ..dep = NA,
        ..group = NA,
        ..design = NA,
        ..con = NA,
        ..escore = NA)
)

equiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equiResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        con = function() private$.items[["con"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Equipercentile Equating")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="con",
                title="Concordance table",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="x", 
                        `type`="integer"),
                    list(
                        `name`="yx", 
                        `type`="number"))))}))

equiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "equiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "equi",
                version = c(1,0,0),
                options = options,
                results = equiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Equipercentile Equating
#'
#' 
#' @param data .
#' @param ind .
#' @param dep .
#' @param group .
#' @param design .
#' @param con .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$con} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$con$asDF}
#'
#' \code{as.data.frame(results$con)}
#'
#' @export
equi <- function(
    data,
    ind,
    dep,
    group,
    design,
    con = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("equi requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ind)) ind <- jmvcore::resolveQuo(jmvcore::enquo(ind))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ind), ind, NULL),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- equiOptions$new(
        ind = ind,
        dep = dep,
        group = group,
        design = design,
        con = con)

    analysis <- equiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

