
# This file is automatically generated, you probably don't want to edit this

lcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covs = NULL,
            nc = 2,
            fit = TRUE,
            comp = TRUE,
            cp = FALSE,
            ip = FALSE,
            cf = FALSE,
            plot = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            angle = 0,
            plot3 = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="lca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=TRUE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..ip <- jmvcore::OptionBool$new(
                "ip",
                ip,
                default=FALSE)
            private$..cf <- jmvcore::OptionBool$new(
                "cf",
                cf,
                default=FALSE)
            private$..cm <- jmvcore::OptionOutput$new(
                "cm")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..covs)
            self$.addOption(private$..nc)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp)
            self$.addOption(private$..cp)
            self$.addOption(private$..ip)
            self$.addOption(private$..cf)
            self$.addOption(private$..cm)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot3)
        }),
    active = list(
        vars = function() private$..vars$value,
        covs = function() private$..covs$value,
        nc = function() private$..nc$value,
        fit = function() private$..fit$value,
        comp = function() private$..comp$value,
        cp = function() private$..cp$value,
        ip = function() private$..ip$value,
        cf = function() private$..cf$value,
        cm = function() private$..cm$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        angle = function() private$..angle$value,
        plot3 = function() private$..plot3$value),
    private = list(
        ..vars = NA,
        ..covs = NA,
        ..nc = NA,
        ..fit = NA,
        ..comp = NA,
        ..cp = NA,
        ..ip = NA,
        ..cf = NA,
        ..cm = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..angle = NA,
        ..plot3 = NA)
)

lcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text1 = function() private$.items[["text1"]],
        fit = function() private$.items[["fit"]],
        comp = function() private$.items[["comp"]],
        cf = function() private$.items[["cf"]],
        cp = function() private$.items[["cp"]],
        ip = function() private$.items[["ip"]],
        text = function() private$.items[["text"]],
        cm = function() private$.items[["cm"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Class Analysis",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs"),
                columns=list(
                    list(
                        `name`="Class", 
                        `type`="number"),
                    list(
                        `name`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="Resid.df", 
                        `type`="number"),
                    list(
                        `name`="AIC", 
                        `type`="number"),
                    list(
                        `name`="BIC", 
                        `type`="number"),
                    list(
                        `name`="ABIC", 
                        `type`="number"),
                    list(
                        `name`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="G\u00B2 p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="\u03C7\u00B2 p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Model comparison",
                visible="(comp)",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="ABIC", 
                        `type`="number"),
                    list(
                        `name`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="Chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="Gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cf",
                title="Predicted cell counts from latent class analysis",
                visible="(cf)",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each latent class",
                visible="(cp)",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="ip",
                title="Item response probabilities",
                visible="(ip)",
                items="(vars)",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Probability of $key",
                    clearWith=list(
                        "vars",
                        "nc",
                        "covs"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Logistic regression coefficients",
                visible="(text)",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs")))
            self$add(jmvcore::Output$new(
                options=options,
                name="cm",
                title="Class membership",
                varTitle="Membership",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="LCA plot",
                visible="(plot)",
                width=600,
                height=450,
                renderFun=".plot",
                refs="poLCA",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Item by class",
                visible="(plot1)",
                width=650,
                height=650,
                renderFun=".plot1",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Profile plot",
                visible="(plot2)",
                renderFun=".plot2",
                refs="snowRMM",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Elbow plot",
                visible="(plot3)",
                width=500,
                height=500,
                refs="snowRMM",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs")))}))

lcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lca",
                version = c(1,0,0),
                options = options,
                results = lcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Latent Class Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param covs .
#' @param nc .
#' @param fit .
#' @param comp .
#' @param cp .
#' @param ip .
#' @param cf .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cf} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ip} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cm} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
lca <- function(
    data,
    vars,
    covs,
    nc = 2,
    fit = TRUE,
    comp = TRUE,
    cp = FALSE,
    ip = FALSE,
    cf = FALSE,
    plot = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    angle = 0,
    plot3 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covs), covs, NULL))


    options <- lcaOptions$new(
        vars = vars,
        covs = covs,
        nc = nc,
        fit = fit,
        comp = comp,
        cp = cp,
        ip = ip,
        cf = cf,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        angle = angle,
        plot3 = plot3)

    analysis <- lcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

