
# This file is automatically generated, you probably don't want to edit this

lcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            nc = 2,
            fit = TRUE,
            comp = TRUE,
            cp = FALSE,
            ip = FALSE,
            cf = FALSE,
            mc = FALSE,
            plot = FALSE,
            angle = 0,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="lca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=TRUE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..ip <- jmvcore::OptionBool$new(
                "ip",
                ip,
                default=FALSE)
            private$..cf <- jmvcore::OptionBool$new(
                "cf",
                cf,
                default=FALSE)
            private$..mc <- jmvcore::OptionBool$new(
                "mc",
                mc,
                default=FALSE)
            private$..cm <- jmvcore::OptionOutput$new(
                "cm")
            private$..pc <- jmvcore::OptionOutput$new(
                "pc")
            private$..post <- jmvcore::OptionOutput$new(
                "post")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=45,
                default=0)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..nc)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp)
            self$.addOption(private$..cp)
            self$.addOption(private$..ip)
            self$.addOption(private$..cf)
            self$.addOption(private$..mc)
            self$.addOption(private$..cm)
            self$.addOption(private$..pc)
            self$.addOption(private$..post)
            self$.addOption(private$..plot)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        nc = function() private$..nc$value,
        fit = function() private$..fit$value,
        comp = function() private$..comp$value,
        cp = function() private$..cp$value,
        ip = function() private$..ip$value,
        cf = function() private$..cf$value,
        mc = function() private$..mc$value,
        cm = function() private$..cm$value,
        pc = function() private$..pc$value,
        post = function() private$..post$value,
        plot = function() private$..plot$value,
        angle = function() private$..angle$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..nc = NA,
        ..fit = NA,
        ..comp = NA,
        ..cp = NA,
        ..ip = NA,
        ..cf = NA,
        ..mc = NA,
        ..cm = NA,
        ..pc = NA,
        ..post = NA,
        ..plot = NA,
        ..angle = NA,
        ..plot1 = NA)
)

lcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        instructions = function() private$.items[["instructions"]],
        fit = function() private$.items[["fit"]],
        comp = function() private$.items[["comp"]],
        cf = function() private$.items[["cf"]],
        cp = function() private$.items[["cp"]],
        ip = function() private$.items[["ip"]],
        mc = function() private$.items[["mc"]],
        cm = function() private$.items[["cm"]],
        pc = function() private$.items[["pc"]],
        post = function() private$.items[["post"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Class Analysis",
                refs="snowRMM")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="test"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                clearWith=list(
                    "vars",
                    "nc"),
                refs="poLCA",
                columns=list(
                    list(
                        `name`="Class", 
                        `type`="number"),
                    list(
                        `name`="AIC", 
                        `type`="number"),
                    list(
                        `name`="BIC", 
                        `type`="number"),
                    list(
                        `name`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="G\u00B2 p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="\u03C7\u00B2 p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Model comparison",
                visible="(comp)",
                clearWith=list(
                    "vars",
                    "nc"),
                refs="poLCA",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="Chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="Gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cf",
                title="Predicted cell counts from latent class analysis",
                visible="(cf)",
                clearWith=list(
                    "vars",
                    "nc"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each latent class",
                visible="(cp)",
                clearWith=list(
                    "vars",
                    "nc"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="ip",
                title="Item response probabilities",
                visible="(ip)",
                items="(vars)",
                clearWith=list(
                    "vars",
                    "nc"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Probability of $key",
                    clearWith=list(
                        "vars",
                        "nc"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mc",
                title="Variable means across membership",
                visible="(mc)",
                clearWith=list(
                    "vars",
                    "nc"),
                refs="snowCluster",
                columns=list(
                    list(
                        `name`=".name[x]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="cm",
                title="Class membership",
                varTitle="Membership",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc")))
            self$add(jmvcore::Output$new(
                options=options,
                name="pc",
                title="Predicted cell percentages",
                varTitle="Cell percentages",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "nc")))
            self$add(jmvcore::Output$new(
                options=options,
                name="post",
                title="Posterior probabilities",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "nc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="LCA plot",
                visible="(plot)",
                width=600,
                height=450,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                visible="(plot1)",
                width=600,
                height=450,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc",
                    "angle")))}))

lcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lca",
                version = c(1,0,0),
                options = options,
                results = lcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Latent Class Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group .
#' @param nc .
#' @param fit .
#' @param comp .
#' @param cp .
#' @param ip .
#' @param cf .
#' @param mc .
#' @param plot .
#' @param angle a number from 0 to 45 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cf} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ip} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$mc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cm} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$pc} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$post} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
lca <- function(
    data,
    vars,
    group,
    nc = 2,
    fit = TRUE,
    comp = TRUE,
    cp = FALSE,
    ip = FALSE,
    cf = FALSE,
    mc = FALSE,
    plot = FALSE,
    angle = 0,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lcaOptions$new(
        vars = vars,
        group = group,
        nc = nc,
        fit = fit,
        comp = comp,
        cp = cp,
        ip = ip,
        cf = cf,
        mc = mc,
        plot = plot,
        angle = angle,
        plot1 = plot1)

    analysis <- lcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

