
# This file is automatically generated, you probably don't want to edit this

lcaordOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nc = 2,
            desc = TRUE,
            fit = FALSE,
            cp = FALSE,
            plot = FALSE,
            width = 500,
            height = 500,
            plot1 = FALSE,
            width1 = 500,
            height1 = 500,
            angle = 0,
            miss = "fiml", ...) {

            super$initialize(
                package="snowRMM",
                name="lcaord",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..mem <- jmvcore::OptionOutput$new(
                "mem")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "listwise",
                    "fiml"),
                default="fiml")

            self$.addOption(private$..vars)
            self$.addOption(private$..nc)
            self$.addOption(private$..desc)
            self$.addOption(private$..fit)
            self$.addOption(private$..cp)
            self$.addOption(private$..mem)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..plot1)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..angle)
            self$.addOption(private$..miss)
        }),
    active = list(
        vars = function() private$..vars$value,
        nc = function() private$..nc$value,
        desc = function() private$..desc$value,
        fit = function() private$..fit$value,
        cp = function() private$..cp$value,
        mem = function() private$..mem$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        plot1 = function() private$..plot1$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        angle = function() private$..angle$value,
        miss = function() private$..miss$value),
    private = list(
        ..vars = NA,
        ..nc = NA,
        ..desc = NA,
        ..fit = NA,
        ..cp = NA,
        ..mem = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..plot1 = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..angle = NA,
        ..miss = NA)
)

lcaordResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        desc = function() private$.items[["desc"]],
        fit = function() private$.items[["fit"]],
        cp = function() private$.items[["cp"]],
        mem = function() private$.items[["mem"]],
        plot1 = function() private$.items[["plot1"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LCA with ordinal indicators",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptive statistics",
                visible="(desc)",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="number"),
                    list(
                        `name`="missing", 
                        `title`="Proportion missing", 
                        `type`="number"),
                    list(
                        `name`="unique", 
                        `title`="Unique", 
                        `type`="number"),
                    list(
                        `name`="mode", 
                        `title`="Mode", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Values"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each class",
                visible="(cp)",
                refs="tidySEM",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="number"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="mem",
                title="Class",
                varTitle="Class",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Bar plot",
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc",
                    "width1",
                    "height1",
                    "miss")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Response probilities",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc",
                    "width",
                    "height",
                    "angle",
                    "miss")))}))

lcaordBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lcaord",
                version = c(1,0,0),
                options = options,
                results = lcaordResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' LCA with ordinal indicators
#'
#' 
#' @param data .
#' @param vars .
#' @param nc .
#' @param desc .
#' @param fit .
#' @param cp .
#' @param plot .
#' @param width .
#' @param height .
#' @param plot1 .
#' @param width1 .
#' @param height1 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param miss .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mem} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$desc$asDF}
#'
#' \code{as.data.frame(results$desc)}
#'
#' @export
lcaord <- function(
    data,
    vars,
    nc = 2,
    desc = TRUE,
    fit = FALSE,
    cp = FALSE,
    plot = FALSE,
    width = 500,
    height = 500,
    plot1 = FALSE,
    width1 = 500,
    height1 = 500,
    angle = 0,
    miss = "fiml") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lcaord requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lcaordOptions$new(
        vars = vars,
        nc = nc,
        desc = desc,
        fit = fit,
        cp = cp,
        plot = plot,
        width = width,
        height = height,
        plot1 = plot1,
        width1 = width1,
        height1 = height1,
        angle = angle,
        miss = miss)

    analysis <- lcaordClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

