
# This file is automatically generated, you probably don't want to edit this

lcaordOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nc = 2,
            desc = TRUE,
            fit = FALSE,
            cp = FALSE,
            plot = FALSE,
            plot1 = FALSE,
            angle = 0,
            miss = "listwise",
            use3step = FALSE,
            auxVar = NULL,
            auxFormula = "depression~peer_support",
            reg = FALSE,
            regvars = NULL, ...) {

            super$initialize(
                package="snowRMM",
                name="lcaord",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..mem <- jmvcore::OptionOutput$new(
                "mem")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "listwise",
                    "fiml"),
                default="listwise")
            private$..use3step <- jmvcore::OptionBool$new(
                "use3step",
                use3step,
                default=FALSE)
            private$..auxVar <- jmvcore::OptionVariable$new(
                "auxVar",
                auxVar,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..auxFormula <- jmvcore::OptionString$new(
                "auxFormula",
                auxFormula,
                default="depression~peer_support")
            private$..reg <- jmvcore::OptionBool$new(
                "reg",
                reg,
                default=FALSE)
            private$..regvars <- jmvcore::OptionVariable$new(
                "regvars",
                regvars,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))

            self$.addOption(private$..vars)
            self$.addOption(private$..nc)
            self$.addOption(private$..desc)
            self$.addOption(private$..fit)
            self$.addOption(private$..cp)
            self$.addOption(private$..mem)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..angle)
            self$.addOption(private$..miss)
            self$.addOption(private$..use3step)
            self$.addOption(private$..auxVar)
            self$.addOption(private$..auxFormula)
            self$.addOption(private$..reg)
            self$.addOption(private$..regvars)
        }),
    active = list(
        vars = function() private$..vars$value,
        nc = function() private$..nc$value,
        desc = function() private$..desc$value,
        fit = function() private$..fit$value,
        cp = function() private$..cp$value,
        mem = function() private$..mem$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        angle = function() private$..angle$value,
        miss = function() private$..miss$value,
        use3step = function() private$..use3step$value,
        auxVar = function() private$..auxVar$value,
        auxFormula = function() private$..auxFormula$value,
        reg = function() private$..reg$value,
        regvars = function() private$..regvars$value),
    private = list(
        ..vars = NA,
        ..nc = NA,
        ..desc = NA,
        ..fit = NA,
        ..cp = NA,
        ..mem = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..angle = NA,
        ..miss = NA,
        ..use3step = NA,
        ..auxVar = NA,
        ..auxFormula = NA,
        ..reg = NA,
        ..regvars = NA)
)

lcaordResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        progressBarHTML = function() private$.items[["progressBarHTML"]],
        desc = function() private$.items[["desc"]],
        fit = function() private$.items[["fit"]],
        cp = function() private$.items[["cp"]],
        mem = function() private$.items[["mem"]],
        plot1 = function() private$.items[["plot1"]],
        plot = function() private$.items[["plot"]],
        use3step = function() private$.items[["use3step"]],
        reg = function() private$.items[["reg"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LCA with ordinal indicators",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="progressBarHTML",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptive statistics",
                visible="(desc)",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="number"),
                    list(
                        `name`="missing", 
                        `title`="Proportion missing", 
                        `type`="number"),
                    list(
                        `name`="unique", 
                        `title`="Unique", 
                        `type`="number"),
                    list(
                        `name`="mode", 
                        `title`="Mode", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Values"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each class",
                visible="(cp)",
                refs="tidySEM",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="number"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="mem",
                title="Class",
                varTitle="Class",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Bar plot",
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc",
                    "miss")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Response probilities",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc",
                    "angle",
                    "miss")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="use3step",
                title="3-step analysis (BCH/DCAT)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Class-wise regression"))}))

lcaordBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaordBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lcaord",
                version = c(1,0,0),
                options = options,
                results = lcaordResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' LCA with ordinal indicators
#'
#' 
#' @param data .
#' @param vars .
#' @param nc .
#' @param desc .
#' @param fit .
#' @param cp .
#' @param plot .
#' @param plot1 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param miss .
#' @param use3step .
#' @param auxVar .
#' @param auxFormula .
#' @param reg .
#' @param regvars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$progressBarHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mem} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$use3step} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$desc$asDF}
#'
#' \code{as.data.frame(results$desc)}
#'
#' @export
lcaord <- function(
    data,
    vars,
    nc = 2,
    desc = TRUE,
    fit = FALSE,
    cp = FALSE,
    plot = FALSE,
    plot1 = FALSE,
    angle = 0,
    miss = "listwise",
    use3step = FALSE,
    auxVar,
    auxFormula = "depression~peer_support",
    reg = FALSE,
    regvars) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lcaord requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(auxVar)) auxVar <- jmvcore::resolveQuo(jmvcore::enquo(auxVar))
    if ( ! missing(regvars)) regvars <- jmvcore::resolveQuo(jmvcore::enquo(regvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(auxVar), auxVar, NULL),
            `if`( ! missing(regvars), regvars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lcaordOptions$new(
        vars = vars,
        nc = nc,
        desc = desc,
        fit = fit,
        cp = cp,
        plot = plot,
        plot1 = plot1,
        angle = angle,
        miss = miss,
        use3step = use3step,
        auxVar = auxVar,
        auxFormula = auxFormula,
        reg = reg,
        regvars = regvars)

    analysis <- lcaordClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

