
# This file is automatically generated, you probably don't want to edit this

lcgmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcgmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            model = list(),
            nc = 2,
            thr = "FALSE",
            fit = FALSE,
            est = FALSE,
            desc = TRUE,
            cp = FALSE,
            plot1 = FALSE,
            plot = FALSE,
            raw = "FALSE",
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowRMM",
                name="lcgm",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionArray$new(
                "model",
                model,
                default=list(),
                template=jmvcore::OptionString$new(
                    "model",
                    NULL))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..thr <- jmvcore::OptionList$new(
                "thr",
                thr,
                options=list(
                    "FALSE",
                    "TRUE"),
                default="FALSE")
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..est <- jmvcore::OptionBool$new(
                "est",
                est,
                default=FALSE)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..mem <- jmvcore::OptionOutput$new(
                "mem")
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..raw <- jmvcore::OptionList$new(
                "raw",
                raw,
                options=list(
                    "FALSE",
                    "TRUE"),
                default="FALSE")
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..model)
            self$.addOption(private$..nc)
            self$.addOption(private$..thr)
            self$.addOption(private$..fit)
            self$.addOption(private$..est)
            self$.addOption(private$..desc)
            self$.addOption(private$..cp)
            self$.addOption(private$..mem)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot)
            self$.addOption(private$..raw)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        model = function() private$..model$value,
        nc = function() private$..nc$value,
        thr = function() private$..thr$value,
        fit = function() private$..fit$value,
        est = function() private$..est$value,
        desc = function() private$..desc$value,
        cp = function() private$..cp$value,
        mem = function() private$..mem$value,
        plot1 = function() private$..plot1$value,
        plot = function() private$..plot$value,
        raw = function() private$..raw$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..model = NA,
        ..nc = NA,
        ..thr = NA,
        ..fit = NA,
        ..est = NA,
        ..desc = NA,
        ..cp = NA,
        ..mem = NA,
        ..plot1 = NA,
        ..plot = NA,
        ..raw = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA)
)

lcgmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcgmResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        desc = function() private$.items[["desc"]],
        fit = function() private$.items[["fit"]],
        est = function() private$.items[["est"]],
        cp = function() private$.items[["cp"]],
        mem = function() private$.items[["mem"]],
        plot1 = function() private$.items[["plot1"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Class Growth Modeling",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptive statistics",
                visible="(desc)",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="number"),
                    list(
                        `name`="missing", 
                        `title`="Proportion missing", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="min", 
                        `title`="Minimum", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Maximum", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Values"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="est",
                title="Estimated parameters",
                visible="(est)",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr"),
                refs="tidySEM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cat", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="lhs", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ci", 
                        `title`="Confidence Interval", 
                        `type`="number"),
                    list(
                        `name`="na", 
                        `title`="name", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each class",
                visible="(cp)",
                refs="tidySEM",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="number"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="mem",
                title="Class",
                varTitle="Class",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Density plot",
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr",
                    "width1",
                    "height1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Trajectory plot",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "model",
                    "nc",
                    "thr",
                    "raw",
                    "width",
                    "height")))}))

lcgmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcgmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lcgm",
                version = c(1,0,0),
                options = options,
                results = lcgmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Latent Class Growth Modeling
#'
#' 
#' @param data .
#' @param vars .
#' @param model .
#' @param nc .
#' @param thr .
#' @param fit .
#' @param est .
#' @param desc .
#' @param cp .
#' @param plot1 .
#' @param plot .
#' @param raw .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$est} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mem} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$desc$asDF}
#'
#' \code{as.data.frame(results$desc)}
#'
#' @export
lcgm <- function(
    data,
    vars,
    model = list(),
    nc = 2,
    thr = "FALSE",
    fit = FALSE,
    est = FALSE,
    desc = TRUE,
    cp = FALSE,
    plot1 = FALSE,
    plot = FALSE,
    raw = "FALSE",
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lcgm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- lcgmOptions$new(
        vars = vars,
        model = model,
        nc = nc,
        thr = thr,
        fit = fit,
        est = est,
        desc = desc,
        cp = cp,
        plot1 = plot1,
        plot = plot,
        raw = raw,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1)

    analysis <- lcgmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

