
# This file is automatically generated, you probably don't want to edit this

linkingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linkingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ind = NULL,
            dep = NULL,
            method = "linear",
            plot = FALSE,
            width = 500,
            height = 500, ...) {

            super$initialize(
                package="snowRMM",
                name="linking",
                requiresData=TRUE,
                ...)

            private$..ind <- jmvcore::OptionVariable$new(
                "ind",
                ind,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "linear",
                    "equipercentile"),
                default="linear")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)

            self$.addOption(private$..ind)
            self$.addOption(private$..dep)
            self$.addOption(private$..method)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
        }),
    active = list(
        ind = function() private$..ind$value,
        dep = function() private$..dep$value,
        method = function() private$..method$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value),
    private = list(
        ..ind = NA,
        ..dep = NA,
        ..method = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA)
)

linkingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linkingResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        con = function() private$.items[["con"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Composite Linking",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="con",
                title="Concordance table",
                refs="equate",
                clearWith=list(
                    "ind",
                    "dep",
                    "method"),
                columns=list(
                    list(
                        `name`="x", 
                        `type`="integer"),
                    list(
                        `name`="yx", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Equating Plot",
                visible="(plot)",
                renderFun=".plot",
                refs="equate",
                clearWith=list(
                    "ind",
                    "dep",
                    "method",
                    "width",
                    "height")))}))

linkingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linkingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "linking",
                version = c(1,0,0),
                options = options,
                results = linkingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Composite Linking
#'
#' 
#' @param data .
#' @param ind .
#' @param dep .
#' @param method .
#' @param plot .
#' @param width .
#' @param height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$con} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$con$asDF}
#'
#' \code{as.data.frame(results$con)}
#'
#' @export
linking <- function(
    data,
    ind,
    dep,
    method = "linear",
    plot = FALSE,
    width = 500,
    height = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("linking requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ind)) ind <- jmvcore::resolveQuo(jmvcore::enquo(ind))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ind), ind, NULL),
            `if`( ! missing(dep), dep, NULL))


    options <- linkingOptions$new(
        ind = ind,
        dep = dep,
        method = method,
        plot = plot,
        width = width,
        height = height)

    analysis <- linkingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

