
# This file is automatically generated, you probably don't want to edit this

lltmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lltmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            mat = "1,0,1,1,1,0,1,0,1,0,1,1,1,1,1,0,0,0,1,1,0,1,0,1,1,  -0.5, 1,  1, -1,0",
            col = 3,
            items = TRUE,
            lr = TRUE,
            ml = TRUE,
            wald = FALSE,
            eta = FALSE,
            beta = FALSE,
            plot = FALSE,
            comp = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="lltm",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..mat <- jmvcore::OptionString$new(
                "mat",
                mat,
                default="1,0,1,1,1,0,1,0,1,0,1,1,1,1,1,0,0,0,1,1,0,1,0,1,1,  -0.5, 1,  1, -1,0")
            private$..col <- jmvcore::OptionInteger$new(
                "col",
                col,
                default=3,
                min=2,
                max=20)
            private$..items <- jmvcore::OptionBool$new(
                "items",
                items,
                default=TRUE)
            private$..lr <- jmvcore::OptionBool$new(
                "lr",
                lr,
                default=TRUE)
            private$..ml <- jmvcore::OptionBool$new(
                "ml",
                ml,
                default=TRUE)
            private$..wald <- jmvcore::OptionBool$new(
                "wald",
                wald,
                default=FALSE)
            private$..eta <- jmvcore::OptionBool$new(
                "eta",
                eta,
                default=FALSE)
            private$..beta <- jmvcore::OptionBool$new(
                "beta",
                beta,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..mat)
            self$.addOption(private$..col)
            self$.addOption(private$..items)
            self$.addOption(private$..lr)
            self$.addOption(private$..ml)
            self$.addOption(private$..wald)
            self$.addOption(private$..eta)
            self$.addOption(private$..beta)
            self$.addOption(private$..plot)
            self$.addOption(private$..comp)
        }),
    active = list(
        vars = function() private$..vars$value,
        mat = function() private$..mat$value,
        col = function() private$..col$value,
        items = function() private$..items$value,
        lr = function() private$..lr$value,
        ml = function() private$..ml$value,
        wald = function() private$..wald$value,
        eta = function() private$..eta$value,
        beta = function() private$..beta$value,
        plot = function() private$..plot$value,
        comp = function() private$..comp$value),
    private = list(
        ..vars = NA,
        ..mat = NA,
        ..col = NA,
        ..items = NA,
        ..lr = NA,
        ..ml = NA,
        ..wald = NA,
        ..eta = NA,
        ..beta = NA,
        ..plot = NA,
        ..comp = NA)
)

lltmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lltmResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        ra = function() private$.items[["ra"]],
        ll = function() private$.items[["ll"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Logisitic Test Model",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    items = function() private$.items[["items"]],
                    lr = function() private$.items[["lr"]],
                    ml = function() private$.items[["ml"]],
                    wald = function() private$.items[["wald"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ra",
                            title="Rasch Model")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="items",
                            title="Rasch item easiness parameters(beta)",
                            visible="(items)",
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="Item", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="item", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="lr",
                            title="Andersen\u2019s LR test",
                            visible="(lr)",
                            rows=1,
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="Likelihood ratio"),
                                list(
                                    `name`="value", 
                                    `title`="Value", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ml",
                            title="Martin-Loef test",
                            visible="(ml)",
                            rows=1,
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="Likelihood ratio"),
                                list(
                                    `name`="value", 
                                    `title`="Value", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="wald",
                            title="Wald test",
                            visible="(wald)",
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="Item", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="item", 
                                    `title`="Z statistic", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `format`="zto, pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eta = function() private$.items[["eta"]],
                    beta = function() private$.items[["beta"]],
                    comp = function() private$.items[["comp"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ll",
                            title="LLTM Model")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eta",
                            title="LLTM Basic item easiness parameters(eta)",
                            visible="(eta)",
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="item", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="beta",
                            title="LLTM Item easiness parameters(beta)",
                            visible="(beta)",
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="Item", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="item", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="comp",
                            title="Analysis of Deviances",
                            visible="(comp)",
                            refs="eRm",
                            clearWith=list(
                                "vars",
                                "mat",
                                "col"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="Model", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="ll", 
                                    `title`="LLs", 
                                    `type`="number"),
                                list(
                                    `name`="dev", 
                                    `title`="Deviance", 
                                    `type`="number"),
                                list(
                                    `name`="npar", 
                                    `title`="npar", 
                                    `type`="number"),
                                list(
                                    `name`="lr", 
                                    `title`="LR", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `format`="zto, pvalue"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Comparison of item easiness parameters ",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "mat",
                    "col")))}))

lltmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lltmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lltm",
                version = c(1,0,0),
                options = options,
                results = lltmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Linear Logisitic Test Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param mat .
#' @param col .
#' @param items .
#' @param lr .
#' @param ml .
#' @param wald .
#' @param eta .
#' @param beta .
#' @param plot .
#' @param comp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ra$items} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ra$lr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ra$ml} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ra$wald} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ll$eta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ll$beta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ll$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
lltm <- function(
    data,
    vars,
    mat = "1,0,1,1,1,0,1,0,1,0,1,1,1,1,1,0,0,0,1,1,0,1,0,1,1,  -0.5, 1,  1, -1,0",
    col = 3,
    items = TRUE,
    lr = TRUE,
    ml = TRUE,
    wald = FALSE,
    eta = FALSE,
    beta = FALSE,
    plot = FALSE,
    comp = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lltm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- lltmOptions$new(
        vars = vars,
        mat = mat,
        col = col,
        items = items,
        lr = lr,
        ml = ml,
        wald = wald,
        eta = eta,
        beta = beta,
        plot = plot,
        comp = comp)

    analysis <- lltmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

