
# This file is automatically generated, you probably don't want to edit this

lpaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nc = 2,
            variances = "equal",
            covariances = "zero",
            fit = TRUE,
            best = FALSE,
            est = FALSE,
            plot = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="lpa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..variances <- jmvcore::OptionList$new(
                "variances",
                variances,
                options=list(
                    "equal",
                    "varying"),
                default="equal")
            private$..covariances <- jmvcore::OptionList$new(
                "covariances",
                covariances,
                options=list(
                    "zero",
                    "equal",
                    "varying"),
                default="zero")
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..best <- jmvcore::OptionBool$new(
                "best",
                best,
                default=FALSE)
            private$..est <- jmvcore::OptionBool$new(
                "est",
                est,
                default=FALSE)
            private$..pc <- jmvcore::OptionOutput$new(
                "pc")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..nc)
            self$.addOption(private$..variances)
            self$.addOption(private$..covariances)
            self$.addOption(private$..fit)
            self$.addOption(private$..best)
            self$.addOption(private$..est)
            self$.addOption(private$..pc)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        nc = function() private$..nc$value,
        variances = function() private$..variances$value,
        covariances = function() private$..covariances$value,
        fit = function() private$..fit$value,
        best = function() private$..best$value,
        est = function() private$..est$value,
        pc = function() private$..pc$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..nc = NA,
        ..variances = NA,
        ..covariances = NA,
        ..fit = NA,
        ..best = NA,
        ..est = NA,
        ..pc = NA,
        ..plot = NA,
        ..plot1 = NA)
)

lpaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        fit = function() private$.items[["fit"]],
        best = function() private$.items[["best"]],
        est = function() private$.items[["est"]],
        pc = function() private$.items[["pc"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Profile Analysis",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                refs="tidyLPA",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Values"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="best",
                title="Class comparison",
                visible="(best)",
                refs="tidyLPA",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="integer"),
                    list(
                        `name`="log", 
                        `title`="LogLik", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="awe", 
                        `title`="AWE", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="clc", 
                        `title`="CLC", 
                        `type`="number"),
                    list(
                        `name`="kic", 
                        `title`="KIC", 
                        `type`="number"),
                    list(
                        `name`="sabic", 
                        `title`="SABIC", 
                        `type`="number"),
                    list(
                        `name`="icl", 
                        `title`="ICL", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="est",
                title="Estimates",
                visible="(est)",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                refs="tidyLPA",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cat", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto, number"),
                    list(
                        `name`="cl", 
                        `title`="Class", 
                        `type`="integer"),
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="integer"),
                    list(
                        `name`="cla", 
                        `title`="Classes", 
                        `type`="integer"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="pc",
                title="Person class",
                varTitle="Class",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Correlation plot for a mixture model",
                visible="(plot)",
                width=600,
                height=600,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Latent profile plot",
                visible="(plot1)",
                width=600,
                height=600,
                refs="tidyLPA",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances")))}))

lpaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lpa",
                version = c(1,0,0),
                options = options,
                results = lpaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Latent Profile Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param nc .
#' @param variances .
#' @param covariances .
#' @param fit .
#' @param best .
#' @param est .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$best} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$est} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pc} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
lpa <- function(
    data,
    vars,
    nc = 2,
    variances = "equal",
    covariances = "zero",
    fit = TRUE,
    best = FALSE,
    est = FALSE,
    plot = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lpa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- lpaOptions$new(
        vars = vars,
        nc = nc,
        variances = variances,
        covariances = covariances,
        fit = fit,
        best = best,
        est = est,
        plot = plot,
        plot1 = plot1)

    analysis <- lpaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

