
# This file is automatically generated, you probably don't want to edit this

lpaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nc = 2,
            variances = "equal",
            covariances = "zero",
            overall = TRUE,
            fit = FALSE,
            est = FALSE,
            plot = FALSE,
            plot1 = FALSE,
            plot3 = FALSE,
            plot2 = FALSE,
            plot4 = FALSE,
            angle = 0,
            line = "FALSE",
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500,
            width3 = 500,
            height3 = 500,
            width4 = 500,
            height4 = 500, ...) {

            super$initialize(
                package="snowRMM",
                name="lpa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..variances <- jmvcore::OptionList$new(
                "variances",
                variances,
                options=list(
                    "equal",
                    "varying"),
                default="equal")
            private$..covariances <- jmvcore::OptionList$new(
                "covariances",
                covariances,
                options=list(
                    "zero",
                    "equal",
                    "varying"),
                default="zero")
            private$..overall <- jmvcore::OptionBool$new(
                "overall",
                overall,
                default=TRUE)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..est <- jmvcore::OptionBool$new(
                "est",
                est,
                default=FALSE)
            private$..pc <- jmvcore::OptionOutput$new(
                "pc")
            private$..post <- jmvcore::OptionOutput$new(
                "post")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "FALSE",
                    "TRUE"),
                default="FALSE")
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)
            private$..width4 <- jmvcore::OptionInteger$new(
                "width4",
                width4,
                default=500)
            private$..height4 <- jmvcore::OptionInteger$new(
                "height4",
                height4,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..nc)
            self$.addOption(private$..variances)
            self$.addOption(private$..covariances)
            self$.addOption(private$..overall)
            self$.addOption(private$..fit)
            self$.addOption(private$..est)
            self$.addOption(private$..pc)
            self$.addOption(private$..post)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot4)
            self$.addOption(private$..angle)
            self$.addOption(private$..line)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
            self$.addOption(private$..width4)
            self$.addOption(private$..height4)
        }),
    active = list(
        vars = function() private$..vars$value,
        nc = function() private$..nc$value,
        variances = function() private$..variances$value,
        covariances = function() private$..covariances$value,
        overall = function() private$..overall$value,
        fit = function() private$..fit$value,
        est = function() private$..est$value,
        pc = function() private$..pc$value,
        post = function() private$..post$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot3 = function() private$..plot3$value,
        plot2 = function() private$..plot2$value,
        plot4 = function() private$..plot4$value,
        angle = function() private$..angle$value,
        line = function() private$..line$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value,
        width4 = function() private$..width4$value,
        height4 = function() private$..height4$value),
    private = list(
        ..vars = NA,
        ..nc = NA,
        ..variances = NA,
        ..covariances = NA,
        ..overall = NA,
        ..fit = NA,
        ..est = NA,
        ..pc = NA,
        ..post = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot3 = NA,
        ..plot2 = NA,
        ..plot4 = NA,
        ..angle = NA,
        ..line = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..width3 = NA,
        ..height3 = NA,
        ..width4 = NA,
        ..height4 = NA)
)

lpaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        overall = function() private$.items[["overall"]],
        fit = function() private$.items[["fit"]],
        est = function() private$.items[["est"]],
        pc = function() private$.items[["pc"]],
        post = function() private$.items[["post"]],
        plot = function() private$.items[["plot"]],
        plot3 = function() private$.items[["plot3"]],
        plot2 = function() private$.items[["plot2"]],
        plot1 = function() private$.items[["plot1"]],
        plot4 = function() private$.items[["plot4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Profile Analysis",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="overall",
                title="Overall model fit",
                visible="(overall)",
                refs="tidyLPA",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="integer"),
                    list(
                        `name`="classes", 
                        `title`="Classes", 
                        `type`="integer"),
                    list(
                        `name`="log", 
                        `title`="LogLik", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="awe", 
                        `title`="AWE", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="clc", 
                        `title`="CLC", 
                        `type`="number"),
                    list(
                        `name`="kic", 
                        `title`="KIC", 
                        `type`="number"),
                    list(
                        `name`="sabic", 
                        `title`="SABIC", 
                        `type`="number"),
                    list(
                        `name`="icl", 
                        `title`="ICL", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                refs="tidyLPA",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Values"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="est",
                title="Estimates",
                visible="(est)",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances"),
                refs="tidyLPA",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cat", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="cl", 
                        `title`="Class", 
                        `type`="integer"),
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="integer"),
                    list(
                        `name`="cla", 
                        `title`="Classes", 
                        `type`="integer"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="pc",
                title="Membership",
                varTitle="Membership",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances")))
            self$add(jmvcore::Output$new(
                options=options,
                name="post",
                title="Posterior",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Percentage of class",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Density plot",
                visible="(plot3)",
                refs="tidyLPA",
                renderFun=".plot3",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances",
                    "width2",
                    "height2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Elbow plot",
                visible="(plot2)",
                refs="snowRMM",
                renderFun=".plot2",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances",
                    "width3",
                    "height3")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Latent profile: Box plot",
                visible="(plot1)",
                refs="tidyLPA",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances",
                    "width1",
                    "height1",
                    "line",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Latent profile: Line plot",
                visible="(plot4)",
                refs="tidyLPA",
                renderFun=".plot4",
                clearWith=list(
                    "vars",
                    "nc",
                    "variances",
                    "covariances",
                    "width4",
                    "height4",
                    "line",
                    "angle")))}))

lpaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lpa",
                version = c(1,0,0),
                options = options,
                results = lpaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Latent Profile Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param nc .
#' @param variances .
#' @param covariances .
#' @param overall .
#' @param fit .
#' @param est .
#' @param plot .
#' @param plot1 .
#' @param plot3 .
#' @param plot2 .
#' @param plot4 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param line .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @param width3 .
#' @param height3 .
#' @param width4 .
#' @param height4 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$overall} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$est} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pc} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$post} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overall$asDF}
#'
#' \code{as.data.frame(results$overall)}
#'
#' @export
lpa <- function(
    data,
    vars,
    nc = 2,
    variances = "equal",
    covariances = "zero",
    overall = TRUE,
    fit = FALSE,
    est = FALSE,
    plot = FALSE,
    plot1 = FALSE,
    plot3 = FALSE,
    plot2 = FALSE,
    plot4 = FALSE,
    angle = 0,
    line = "FALSE",
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500,
    width3 = 500,
    height3 = 500,
    width4 = 500,
    height4 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lpa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- lpaOptions$new(
        vars = vars,
        nc = nc,
        variances = variances,
        covariances = covariances,
        overall = overall,
        fit = fit,
        est = est,
        plot = plot,
        plot1 = plot1,
        plot3 = plot3,
        plot2 = plot2,
        plot4 = plot4,
        angle = angle,
        line = line,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2,
        width3 = width3,
        height3 = height3,
        width4 = width4,
        height4 = height4)

    analysis <- lpaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

