
# This file is automatically generated, you probably don't want to edit this

lpaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nc = 2,
            fit = TRUE,
            plot = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="lpa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..nc)
            self$.addOption(private$..fit)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        nc = function() private$..nc$value,
        fit = function() private$..fit$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..nc = NA,
        ..fit = NA,
        ..plot = NA,
        ..plot1 = NA)
)

lpaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Profile Analysis",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model fit"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Correlation plot for a mixture model",
                visible="(plot)",
                width=600,
                height=600,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "nc")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Latent profile plot",
                visible="(plot1)",
                width=600,
                height=600,
                refs="tidyLPA",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "nc")))}))

lpaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lpaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "lpa",
                version = c(1,0,0),
                options = options,
                results = lpaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Latent Profile Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param nc .
#' @param fit .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
lpa <- function(
    data,
    vars,
    nc = 2,
    fit = TRUE,
    plot = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lpa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- lpaOptions$new(
        vars = vars,
        nc = nc,
        fit = fit,
        plot = plot,
        plot1 = plot1)

    analysis <- lpaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

