
# This file is automatically generated, you probably don't want to edit this

pfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "bi",
            adj = "BH",
            bn = 100,
            outfit = TRUE,
            infit = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="pfit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "bi",
                    "ra"),
                default="bi")
            private$..adj <- jmvcore::OptionList$new(
                "adj",
                adj,
                options=list(
                    "BH",
                    "holm",
                    "hochberg",
                    "hommel",
                    "bonferroni",
                    "BY"),
                default="BH")
            private$..bn <- jmvcore::OptionInteger$new(
                "bn",
                bn,
                min=2,
                default=100)
            private$..outfit <- jmvcore::OptionBool$new(
                "outfit",
                outfit,
                default=TRUE)
            private$..infit <- jmvcore::OptionBool$new(
                "infit",
                infit,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..adj)
            self$.addOption(private$..bn)
            self$.addOption(private$..outfit)
            self$.addOption(private$..infit)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        adj = function() private$..adj$value,
        bn = function() private$..bn$value,
        outfit = function() private$..outfit$value,
        infit = function() private$..infit$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..adj = NA,
        ..bn = NA,
        ..outfit = NA,
        ..infit = NA)
)

pfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pfitResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        outfit = function() private$.items[["outfit"]],
        infit = function() private$.items[["infit"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrap item fit with P values",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="outfit",
                title="Bootstrap Outfit Statistics",
                visible="(outfit)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "type",
                    "bn",
                    "adj"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="fit", 
                        `title`="Outfit"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="adp", 
                        `title`="Adj.p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="infit",
                title="Bootstrap Infit Statistics",
                visible="(infit)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "type",
                    "bn",
                    "adj"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="fit", 
                        `title`="Infit"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="adp", 
                        `title`="Adj.p", 
                        `format`="zto,pvalue"))))}))

pfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "pfit",
                version = c(1,0,0),
                options = options,
                results = pfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bootstrap item fit with P values
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param adj .
#' @param bn .
#' @param outfit .
#' @param infit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$infit} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$outfit$asDF}
#'
#' \code{as.data.frame(results$outfit)}
#'
#' @export
pfit <- function(
    data,
    vars,
    type = "bi",
    adj = "BH",
    bn = 100,
    outfit = TRUE,
    infit = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- pfitOptions$new(
        vars = vars,
        type = type,
        adj = adj,
        bn = bn,
        outfit = outfit,
        infit = infit)

    analysis <- pfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

