
# This file is automatically generated, you probably don't want to edit this

raschOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raschOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            num = 1,
            step = 1,
            type = "RSM",
            fit = TRUE,
            imean = TRUE,
            imeasure = TRUE,
            ise = FALSE,
            infit = FALSE,
            outfit = FALSE,
            pbis = FALSE,
            rsm = FALSE,
            pcm = FALSE,
            wrightmap = TRUE,
            lrsplit = "median",
            mlsplit = "median",
            waldsplit = "median",
            lr = FALSE,
            ml = FALSE,
            ml1 = FALSE,
            mlsplit1 = "median",
            wald = FALSE,
            gofplot = FALSE,
            tlab = "item",
            inplot = FALSE,
            outplot = FALSE,
            angle = 0,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            piplot = FALSE, ...) {

            super$initialize(
                package="snowRMM",
                name="rasch",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..num <- jmvcore::OptionInteger$new(
                "num",
                num,
                default=1,
                min=1)
            private$..step <- jmvcore::OptionInteger$new(
                "step",
                step,
                min=1,
                default=1)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "RSM",
                    "PCM"),
                default="RSM")
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..imean <- jmvcore::OptionBool$new(
                "imean",
                imean,
                default=TRUE)
            private$..imeasure <- jmvcore::OptionBool$new(
                "imeasure",
                imeasure,
                default=TRUE)
            private$..ise <- jmvcore::OptionBool$new(
                "ise",
                ise,
                default=FALSE)
            private$..infit <- jmvcore::OptionBool$new(
                "infit",
                infit,
                default=FALSE)
            private$..outfit <- jmvcore::OptionBool$new(
                "outfit",
                outfit,
                default=FALSE)
            private$..pbis <- jmvcore::OptionBool$new(
                "pbis",
                pbis,
                default=FALSE)
            private$..rsm <- jmvcore::OptionBool$new(
                "rsm",
                rsm,
                default=FALSE)
            private$..pcm <- jmvcore::OptionBool$new(
                "pcm",
                pcm,
                default=FALSE)
            private$..wrightmap <- jmvcore::OptionBool$new(
                "wrightmap",
                wrightmap,
                default=TRUE)
            private$..total <- jmvcore::OptionOutput$new(
                "total")
            private$..pmeasure <- jmvcore::OptionOutput$new(
                "pmeasure")
            private$..pse <- jmvcore::OptionOutput$new(
                "pse")
            private$..pinfit <- jmvcore::OptionOutput$new(
                "pinfit")
            private$..poutfit <- jmvcore::OptionOutput$new(
                "poutfit")
            private$..lrsplit <- jmvcore::OptionList$new(
                "lrsplit",
                lrsplit,
                options=list(
                    "median",
                    "mean"),
                default="median")
            private$..mlsplit <- jmvcore::OptionList$new(
                "mlsplit",
                mlsplit,
                options=list(
                    "median",
                    "mean"),
                default="median")
            private$..waldsplit <- jmvcore::OptionList$new(
                "waldsplit",
                waldsplit,
                options=list(
                    "median",
                    "mean"),
                default="median")
            private$..lr <- jmvcore::OptionBool$new(
                "lr",
                lr,
                default=FALSE)
            private$..ml <- jmvcore::OptionBool$new(
                "ml",
                ml,
                default=FALSE)
            private$..ml1 <- jmvcore::OptionBool$new(
                "ml1",
                ml1,
                default=FALSE)
            private$..mlsplit1 <- jmvcore::OptionList$new(
                "mlsplit1",
                mlsplit1,
                options=list(
                    "median",
                    "mean"),
                default="median")
            private$..wald <- jmvcore::OptionBool$new(
                "wald",
                wald,
                default=FALSE)
            private$..gofplot <- jmvcore::OptionBool$new(
                "gofplot",
                gofplot,
                default=FALSE)
            private$..tlab <- jmvcore::OptionList$new(
                "tlab",
                tlab,
                options=list(
                    "item",
                    "number"),
                default="item")
            private$..inplot <- jmvcore::OptionBool$new(
                "inplot",
                inplot,
                default=FALSE)
            private$..outplot <- jmvcore::OptionBool$new(
                "outplot",
                outplot,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=45,
                default=0)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..piplot <- jmvcore::OptionBool$new(
                "piplot",
                piplot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..num)
            self$.addOption(private$..step)
            self$.addOption(private$..type)
            self$.addOption(private$..fit)
            self$.addOption(private$..imean)
            self$.addOption(private$..imeasure)
            self$.addOption(private$..ise)
            self$.addOption(private$..infit)
            self$.addOption(private$..outfit)
            self$.addOption(private$..pbis)
            self$.addOption(private$..rsm)
            self$.addOption(private$..pcm)
            self$.addOption(private$..wrightmap)
            self$.addOption(private$..total)
            self$.addOption(private$..pmeasure)
            self$.addOption(private$..pse)
            self$.addOption(private$..pinfit)
            self$.addOption(private$..poutfit)
            self$.addOption(private$..lrsplit)
            self$.addOption(private$..mlsplit)
            self$.addOption(private$..waldsplit)
            self$.addOption(private$..lr)
            self$.addOption(private$..ml)
            self$.addOption(private$..ml1)
            self$.addOption(private$..mlsplit1)
            self$.addOption(private$..wald)
            self$.addOption(private$..gofplot)
            self$.addOption(private$..tlab)
            self$.addOption(private$..inplot)
            self$.addOption(private$..outplot)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..piplot)
        }),
    active = list(
        vars = function() private$..vars$value,
        num = function() private$..num$value,
        step = function() private$..step$value,
        type = function() private$..type$value,
        fit = function() private$..fit$value,
        imean = function() private$..imean$value,
        imeasure = function() private$..imeasure$value,
        ise = function() private$..ise$value,
        infit = function() private$..infit$value,
        outfit = function() private$..outfit$value,
        pbis = function() private$..pbis$value,
        rsm = function() private$..rsm$value,
        pcm = function() private$..pcm$value,
        wrightmap = function() private$..wrightmap$value,
        total = function() private$..total$value,
        pmeasure = function() private$..pmeasure$value,
        pse = function() private$..pse$value,
        pinfit = function() private$..pinfit$value,
        poutfit = function() private$..poutfit$value,
        lrsplit = function() private$..lrsplit$value,
        mlsplit = function() private$..mlsplit$value,
        waldsplit = function() private$..waldsplit$value,
        lr = function() private$..lr$value,
        ml = function() private$..ml$value,
        ml1 = function() private$..ml1$value,
        mlsplit1 = function() private$..mlsplit1$value,
        wald = function() private$..wald$value,
        gofplot = function() private$..gofplot$value,
        tlab = function() private$..tlab$value,
        inplot = function() private$..inplot$value,
        outplot = function() private$..outplot$value,
        angle = function() private$..angle$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        piplot = function() private$..piplot$value),
    private = list(
        ..vars = NA,
        ..num = NA,
        ..step = NA,
        ..type = NA,
        ..fit = NA,
        ..imean = NA,
        ..imeasure = NA,
        ..ise = NA,
        ..infit = NA,
        ..outfit = NA,
        ..pbis = NA,
        ..rsm = NA,
        ..pcm = NA,
        ..wrightmap = NA,
        ..total = NA,
        ..pmeasure = NA,
        ..pse = NA,
        ..pinfit = NA,
        ..poutfit = NA,
        ..lrsplit = NA,
        ..mlsplit = NA,
        ..waldsplit = NA,
        ..lr = NA,
        ..ml = NA,
        ..ml1 = NA,
        ..mlsplit1 = NA,
        ..wald = NA,
        ..gofplot = NA,
        ..tlab = NA,
        ..inplot = NA,
        ..outplot = NA,
        ..angle = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..piplot = NA)
)

raschResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raschResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        item = function() private$.items[["item"]],
        rsm = function() private$.items[["rsm"]],
        pcm = function() private$.items[["pcm"]],
        plot = function() private$.items[["plot"]],
        piplot = function() private$.items[["piplot"]],
        gofplot = function() private$.items[["gofplot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        inplot = function() private$.items[["inplot"]],
        outplot = function() private$.items[["outplot"]],
        total = function() private$.items[["total"]],
        pmeasure = function() private$.items[["pmeasure"]],
        pse = function() private$.items[["pse"]],
        pinfit = function() private$.items[["pinfit"]],
        poutfit = function() private$.items[["poutfit"]],
        lr = function() private$.items[["lr"]],
        ml = function() private$.items[["ml"]],
        ml1 = function() private$.items[["ml1"]],
        wald = function() private$.items[["wald"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Rasch Model",
                refs="snowRMM")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    model = function() private$.items[["model"]],
                    items = function() private$.items[["items"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="item",
                            title="Item Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="model",
                            title="`Model information - ${type}`",
                            rows=1,
                            visible="(fit)",
                            clearWith=list(
                                "vars",
                                "step",
                                "type"),
                            refs="mixRasch",
                            columns=list(
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `type`="number"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number"),
                                list(
                                    `name`="caic", 
                                    `title`="CAIC", 
                                    `type`="number"),
                                list(
                                    `name`="loglik", 
                                    `title`="Log-likelihood", 
                                    `type`="number"),
                                list(
                                    `name`="parm", 
                                    `title`="Parameters", 
                                    `type`="integer"),
                                list(
                                    `name`="person", 
                                    `title`="Persons", 
                                    `type`="integer"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="items",
                            title="`Item statistics - ${type}`",
                            visible="(imean || imeasure || ise || infit || outfit || pbis)",
                            rows="(vars)",
                            clearWith=list(
                                "vars",
                                "step",
                                "type"),
                            refs="mixRasch",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="imean", 
                                    `title`="Item mean", 
                                    `visible`="(imean)"),
                                list(
                                    `name`="imeasure", 
                                    `title`="Measure", 
                                    `visible`="(imeasure)"),
                                list(
                                    `name`="ise", 
                                    `title`="S.E.Measure", 
                                    `visible`="(ise)"),
                                list(
                                    `name`="infit", 
                                    `title`="Infit", 
                                    `visible`="(infit)"),
                                list(
                                    `name`="outfit", 
                                    `title`="Outfit", 
                                    `visible`="(outfit)"),
                                list(
                                    `name`="pbis", 
                                    `title`="Point biserial", 
                                    `visible`="(pbis)"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="rsm",
                title="Thresholds of Rating Scale Model",
                rows="(vars)",
                visible="(rsm)",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="number", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pcm",
                title="Thresholds of Partial Credit Model",
                rows="(vars)",
                visible="(pcm)",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="number", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Wright Map",
                width=500,
                height=500,
                visible="(wrightmap)",
                renderFun=".plot",
                requiresData=TRUE,
                refs="ShinyItemAnalysis",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Image$new(
                options=options,
                name="piplot",
                title="Person-Item Map for Partial Credit Model ",
                width=500,
                height=500,
                visible="(piplot)",
                renderFun=".piPlot",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Image$new(
                options=options,
                name="gofplot",
                title="Goodness-of-Fit for LR test",
                width=500,
                height=500,
                visible="(gofplot)",
                renderFun=".gofplot",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "lrsplit",
                    "tlab")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="ICC for Dichotomous Item",
                width=500,
                height=500,
                visible="(plot1)",
                renderFun=".plot1",
                requiresData=TRUE,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "num")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Category for Rating Scale Model",
                width=500,
                height=500,
                visible="(plot2)",
                renderFun=".plot2",
                requiresData=TRUE,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "num")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Category for Partial Credit Model",
                width=500,
                height=500,
                visible="(plot3)",
                renderFun=".plot3",
                requiresData=TRUE,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "num")))
            self$add(jmvcore::Image$new(
                options=options,
                name="inplot",
                title="Item Infit plot",
                width=500,
                height=500,
                visible="(inplot)",
                renderFun=".inPlot",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="outplot",
                title="Item Outfit plot",
                width=500,
                height=500,
                visible="(outplot)",
                renderFun=".outPlot",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "angle")))
            self$add(jmvcore::Output$new(
                options=options,
                name="total",
                title="Total",
                varTitle="Total",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Output$new(
                options=options,
                name="pmeasure",
                title="Measure",
                varTitle="Measure",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Output$new(
                options=options,
                name="pse",
                title="SE",
                varTitle="SE",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Output$new(
                options=options,
                name="pinfit",
                title="Person Infit",
                varTitle="Infit",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Output$new(
                options=options,
                name="poutfit",
                title="Person Outfit",
                varTitle="Outfit",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "step",
                    "type")))
            self$add(jmvcore::Table$new(
                options=options,
                name="lr",
                title="`Andersen\u2019s LR test - ${lrsplit}`",
                visible="(lr)",
                rows=1,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "lrsplit"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Likelihood ratio"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ml",
                title="`Martin-Loef test - ${mlsplit}`",
                visible="(ml)",
                rows=1,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "mlsplit"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Likelihood ratio"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ml1",
                title="`Martin-Loef test - ${mlsplit1}`",
                visible="(ml1)",
                rows=1,
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "mlsplit1"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Likelihood ratio"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="wald",
                title="`Wald test - ${waldsplit}`",
                visible="(wald)",
                refs="eRm",
                clearWith=list(
                    "vars",
                    "step",
                    "type",
                    "waldsplit"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Item", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="item", 
                        `title`="Z statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto, pvalue"))))}))

raschBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raschBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowRMM",
                name = "rasch",
                version = c(1,0,0),
                options = options,
                results = raschResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Rasch Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param num .
#' @param step .
#' @param type .
#' @param fit .
#' @param imean .
#' @param imeasure .
#' @param ise .
#' @param infit .
#' @param outfit .
#' @param pbis .
#' @param rsm .
#' @param pcm .
#' @param wrightmap .
#' @param lrsplit .
#' @param mlsplit .
#' @param waldsplit .
#' @param lr .
#' @param ml .
#' @param ml1 .
#' @param mlsplit1 .
#' @param wald .
#' @param gofplot .
#' @param tlab .
#' @param inplot .
#' @param outplot .
#' @param angle a number from 0 to 45 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param piplot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$item$model} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item$items} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rsm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pcm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$piplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$gofplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$outplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$total} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$pmeasure} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$pse} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$pinfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$poutfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$lr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ml} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ml1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$wald} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$rsm$asDF}
#'
#' \code{as.data.frame(results$rsm)}
#'
#' @export
rasch <- function(
    data,
    vars,
    num = 1,
    step = 1,
    type = "RSM",
    fit = TRUE,
    imean = TRUE,
    imeasure = TRUE,
    ise = FALSE,
    infit = FALSE,
    outfit = FALSE,
    pbis = FALSE,
    rsm = FALSE,
    pcm = FALSE,
    wrightmap = TRUE,
    lrsplit = "median",
    mlsplit = "median",
    waldsplit = "median",
    lr = FALSE,
    ml = FALSE,
    ml1 = FALSE,
    mlsplit1 = "median",
    wald = FALSE,
    gofplot = FALSE,
    tlab = "item",
    inplot = FALSE,
    outplot = FALSE,
    angle = 0,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    piplot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rasch requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- raschOptions$new(
        vars = vars,
        num = num,
        step = step,
        type = type,
        fit = fit,
        imean = imean,
        imeasure = imeasure,
        ise = ise,
        infit = infit,
        outfit = outfit,
        pbis = pbis,
        rsm = rsm,
        pcm = pcm,
        wrightmap = wrightmap,
        lrsplit = lrsplit,
        mlsplit = mlsplit,
        waldsplit = waldsplit,
        lr = lr,
        ml = ml,
        ml1 = ml1,
        mlsplit1 = mlsplit1,
        wald = wald,
        gofplot = gofplot,
        tlab = tlab,
        inplot = inplot,
        outplot = outplot,
        angle = angle,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        piplot = piplot)

    analysis <- raschClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

