
# This file is automatically generated, you probably don't want to edit this

raschOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "raschOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            step = 1,
            type = "RSM",
            aic = TRUE,
            bic = TRUE,
            caic = FALSE,
            imean = TRUE,
            imeasure = TRUE,
            ise = TRUE,
            infit = FALSE,
            outfit = FALSE,
            pbis = FALSE,
            bfit = FALSE,
            total = TRUE,
            pmeasure = TRUE,
            pse = TRUE,
            pinfit = FALSE,
            poutfit = FALSE,
            wrightmap = FALSE, ...) {

            super$initialize(
                package='snowRMM',
                name='rasch',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..step <- jmvcore::OptionInteger$new(
                "step",
                step,
                min=1,
                default=1)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "RSM",
                    "PCM"),
                default="RSM")
            private$..aic <- jmvcore::OptionBool$new(
                "aic",
                aic,
                default=TRUE)
            private$..bic <- jmvcore::OptionBool$new(
                "bic",
                bic,
                default=TRUE)
            private$..caic <- jmvcore::OptionBool$new(
                "caic",
                caic,
                default=FALSE)
            private$..imean <- jmvcore::OptionBool$new(
                "imean",
                imean,
                default=TRUE)
            private$..imeasure <- jmvcore::OptionBool$new(
                "imeasure",
                imeasure,
                default=TRUE)
            private$..ise <- jmvcore::OptionBool$new(
                "ise",
                ise,
                default=TRUE)
            private$..infit <- jmvcore::OptionBool$new(
                "infit",
                infit,
                default=FALSE)
            private$..outfit <- jmvcore::OptionBool$new(
                "outfit",
                outfit,
                default=FALSE)
            private$..pbis <- jmvcore::OptionBool$new(
                "pbis",
                pbis,
                default=FALSE)
            private$..bfit <- jmvcore::OptionBool$new(
                "bfit",
                bfit,
                default=FALSE)
            private$..total <- jmvcore::OptionBool$new(
                "total",
                total,
                default=TRUE)
            private$..pmeasure <- jmvcore::OptionBool$new(
                "pmeasure",
                pmeasure,
                default=TRUE)
            private$..pse <- jmvcore::OptionBool$new(
                "pse",
                pse,
                default=TRUE)
            private$..pinfit <- jmvcore::OptionBool$new(
                "pinfit",
                pinfit,
                default=FALSE)
            private$..poutfit <- jmvcore::OptionBool$new(
                "poutfit",
                poutfit,
                default=FALSE)
            private$..wrightmap <- jmvcore::OptionBool$new(
                "wrightmap",
                wrightmap,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..step)
            self$.addOption(private$..type)
            self$.addOption(private$..aic)
            self$.addOption(private$..bic)
            self$.addOption(private$..caic)
            self$.addOption(private$..imean)
            self$.addOption(private$..imeasure)
            self$.addOption(private$..ise)
            self$.addOption(private$..infit)
            self$.addOption(private$..outfit)
            self$.addOption(private$..pbis)
            self$.addOption(private$..bfit)
            self$.addOption(private$..total)
            self$.addOption(private$..pmeasure)
            self$.addOption(private$..pse)
            self$.addOption(private$..pinfit)
            self$.addOption(private$..poutfit)
            self$.addOption(private$..wrightmap)
        }),
    active = list(
        vars = function() private$..vars$value,
        step = function() private$..step$value,
        type = function() private$..type$value,
        aic = function() private$..aic$value,
        bic = function() private$..bic$value,
        caic = function() private$..caic$value,
        imean = function() private$..imean$value,
        imeasure = function() private$..imeasure$value,
        ise = function() private$..ise$value,
        infit = function() private$..infit$value,
        outfit = function() private$..outfit$value,
        pbis = function() private$..pbis$value,
        bfit = function() private$..bfit$value,
        total = function() private$..total$value,
        pmeasure = function() private$..pmeasure$value,
        pse = function() private$..pse$value,
        pinfit = function() private$..pinfit$value,
        poutfit = function() private$..poutfit$value,
        wrightmap = function() private$..wrightmap$value),
    private = list(
        ..vars = NA,
        ..step = NA,
        ..type = NA,
        ..aic = NA,
        ..bic = NA,
        ..caic = NA,
        ..imean = NA,
        ..imeasure = NA,
        ..ise = NA,
        ..infit = NA,
        ..outfit = NA,
        ..pbis = NA,
        ..bfit = NA,
        ..total = NA,
        ..pmeasure = NA,
        ..pse = NA,
        ..pinfit = NA,
        ..poutfit = NA,
        ..wrightmap = NA)
)

raschResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        item = function() private$.items[["item"]],
        person = function() private$.items[["person"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Rasch Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="RMM"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    model = function() private$.items[["model"]],
                    items = function() private$.items[["items"]],
                    bfit = function() private$.items[["bfit"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="item",
                            title="Item Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="model",
                            title="Model Information",
                            rows=1,
                            clearWith=list(
                                "vars"),
                            refs="mixRasch",
                            columns=list(
                                list(
                                    `name`="class", 
                                    `title`="Class", 
                                    `visible`="(class)"),
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `visible`="(aic)"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `visible`="(bic)"),
                                list(
                                    `name`="caic", 
                                    `title`="CAIC", 
                                    `visible`="(caic)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="items",
                            title="Item Statistics",
                            visible="(imean || imeasure || ise || infit || outfit || pbis)",
                            rows="(vars)",
                            clearWith=list(
                                "vars"),
                            refs="mixRasch",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="imean", 
                                    `title`="Item mean", 
                                    `visible`="(imean)"),
                                list(
                                    `name`="imeasure", 
                                    `title`="Measure", 
                                    `visible`="(imeasure)"),
                                list(
                                    `name`="ise", 
                                    `title`="S.E.Measure", 
                                    `visible`="(ise)"),
                                list(
                                    `name`="infit", 
                                    `title`="Infit", 
                                    `visible`="(infit)"),
                                list(
                                    `name`="outfit", 
                                    `title`="Outfit", 
                                    `visible`="(outfit)"),
                                list(
                                    `name`="pbis", 
                                    `title`="Point biserial", 
                                    `visible`="(pbis)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="bfit",
                            title="Bootstrap item fit",
                            visible="(bfit)",
                            rows=1,
                            clearWith=list(
                                "vars"),
                            columns=list(
                                list(
                                    `name`="binfit[in]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="Infit"),
                                list(
                                    `name`="binfit[out]", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="Outfit"),
                                list(
                                    `name`="l[infit]", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="u[infit]", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="l[outfit]", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `superTitle`="95% CI"),
                                list(
                                    `name`="u[outfit]", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `superTitle`="95% CI"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    persons = function() private$.items[["persons"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="person",
                            title="Person Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="persons",
                            title="Person Statistics",
                            visible="(total || pmeasure || pse || pinfit || poutfit)",
                            clearWith=list(
                                "vars"),
                            refs="mixRasch",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="total", 
                                    `title`="Total score", 
                                    `visible`="(total)"),
                                list(
                                    `name`="pmeasure", 
                                    `title`="Measure", 
                                    `visible`="(pmeasure)"),
                                list(
                                    `name`="pse", 
                                    `title`="S.E.Measure", 
                                    `visible`="(pse)"),
                                list(
                                    `name`="pinfit", 
                                    `title`="Infit", 
                                    `visible`="(pinfit)"),
                                list(
                                    `name`="poutfit", 
                                    `title`="Outfit", 
                                    `visible`="(poutfit)"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Wright Map",
                width=600,
                height=450,
                visible="(wrightmap)",
                renderFun=".plot",
                requiresData=TRUE,
                refs="mixRasch"))}))

raschBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "raschBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowRMM',
                name = 'rasch',
                version = c(1,0,0),
                options = options,
                results = raschResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Rasch Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param step .
#' @param type .
#' @param aic .
#' @param bic .
#' @param caic .
#' @param imean .
#' @param imeasure .
#' @param ise .
#' @param infit .
#' @param outfit .
#' @param pbis .
#' @param bfit .
#' @param total .
#' @param pmeasure .
#' @param pse .
#' @param pinfit .
#' @param poutfit .
#' @param wrightmap .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$item$model} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item$items} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item$bfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$person$persons} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
rasch <- function(
    data,
    vars,
    step = 1,
    type = "RSM",
    aic = TRUE,
    bic = TRUE,
    caic = FALSE,
    imean = TRUE,
    imeasure = TRUE,
    ise = TRUE,
    infit = FALSE,
    outfit = FALSE,
    pbis = FALSE,
    bfit = FALSE,
    total = TRUE,
    pmeasure = TRUE,
    pse = TRUE,
    pinfit = FALSE,
    poutfit = FALSE,
    wrightmap = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('rasch requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- raschOptions$new(
        vars = vars,
        step = step,
        type = type,
        aic = aic,
        bic = bic,
        caic = caic,
        imean = imean,
        imeasure = imeasure,
        ise = ise,
        infit = infit,
        outfit = outfit,
        pbis = pbis,
        bfit = bfit,
        total = total,
        pmeasure = pmeasure,
        pse = pse,
        pinfit = pinfit,
        poutfit = poutfit,
        wrightmap = wrightmap)

    analysis <- raschClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
